### ISSUE TITLE
Doesn't work with ncc 0.19.1

### ISSUE THREAD

**Issue by Janpot** [jaydp17/serverless-plugin-ncc#7]
after upgrading `ncc` from `0.18.5` to `0.19.1` I'm getting errors like:
```
Serverless: running ncc
ncc: Version 0.19.1
ncc: Compiling file /project-folder/handler.js
archive error { Error: input source must be valid Stream or Buffer instance
    at Archiver.append (/project-folder/node_modules/archiver/lib/core.js:575:24)
    at append (/project-folder/node_modules/serverless-plugin-ncc/src/zipper.ts:54:15)
    at new Promise (<anonymous>)
    at /project-folder/node_modules/serverless-plugin-ncc/src/zipper.ts:17:10
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/project-folder/node_modules/serverless-plugin-ncc/dist/zipper.js:14:103)
    at _next (/project-folder/node_modules/serverless-plugin-ncc/dist/zipper.js:16:194)
    at /project-folder/node_modules/serverless-plugin-ncc/dist/zipper.js:16:364
    at new Promise (<anonymous>)
    at /project-folder/node_modules/serverless-plugin-ncc/dist/zipper.js:16:97
    at _createZip (/project-folder/node_modules/serverless-plugin-ncc/dist/zipper.js:76:21)
    at createZip (/project-folder/node_modules/serverless-plugin-ncc/dist/zipper.js:19:21)
    at /project-folder/node_modules/serverless-plugin-ncc/src/index.ts:44:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/project-folder/node_modules/serverless-plugin-ncc/dist/index.js:24:103)
    at _next (/project-folder/node_modules/serverless-plugin-ncc/dist/index.js:26:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'input source must be valid Stream or Buffer instance',
  code: 'INPUTSTEAMBUFFERREQUIRED',
  data: { name: 'handler.js' } }
```

**Comment by jaydp17** [comment]
@Janpot can you please create a reproducible sample repo for this?

**Comment by Janpot** [comment]
`ncc@0.20.1` was released since and it seems to have fixed the issue. (It just happens with `0.19.1` on the basic hello world example from the serverless homepage btw)
